# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-08 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='secType',
            new_name='sec_type',
        ),
    ]
