# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170308_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='subscribe',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
