# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-08 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(db_index=True, null=True)),
                ('ask', models.FloatField(null=True)),
                ('asksize', models.FloatField(null=True)),
                ('bid', models.FloatField(null=True)),
                ('bidsize', models.FloatField(null=True)),
                ('date', models.DateTimeField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('crawl_source', models.CharField(blank=True, default=b'', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(db_index=True, null=True)),
                ('date', models.DateTimeField(db_index=True, null=True)),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('change', models.FloatField(null=True)),
                ('settle', models.FloatField(null=True)),
                ('open_interest', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('wap', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('crawl_source', models.CharField(blank=True, default=b'', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(db_index=True, max_length=255, null=True)),
                ('sym', models.CharField(db_index=True, max_length=255, null=True)),
                ('cur', models.CharField(db_index=True, max_length=255, null=True)),
                ('exch', models.CharField(db_index=True, max_length=255, null=True)),
                ('secType', models.CharField(db_index=True, max_length=255, null=True)),
                ('trade_freq', models.IntegerField(db_index=True, null=True)),
                ('mult', models.FloatField(db_index=True, max_length=255, null=True)),
                ('local_sym', models.CharField(db_index=True, max_length=255, null=True)),
                ('contractMonth', models.CharField(db_index=True, max_length=255, null=True)),
                ('expiry', models.CharField(db_index=True, max_length=255, null=True)),
                ('evRule', models.CharField(db_index=True, max_length=255, null=True)),
                ('liquidHours', models.CharField(db_index=True, max_length=255, null=True)),
                ('longName', models.CharField(db_index=True, max_length=255, null=True)),
                ('minTick', models.FloatField(db_index=True, max_length=255, null=True)),
                ('timeZoneId', models.CharField(db_index=True, max_length=255, null=True)),
                ('tradingHours', models.CharField(db_index=True, max_length=255, null=True)),
                ('underConId', models.IntegerField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('crawl_source', models.CharField(blank=True, default=b'', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(db_index=True, null=True)),
                ('pred_start_date', models.DateTimeField(db_index=True, null=True)),
                ('date', models.DateTimeField(db_index=True, null=True)),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('wap', models.FloatField(null=True)),
                ('algo_name', models.CharField(blank=True, default=b'', max_length=200, null=True)),
                ('is_scaled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('crawl_source', models.CharField(blank=True, default=b'', max_length=200, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(blank=True, db_index=True, default=b'Energy', max_length=50)),
                ('commodity_type', models.CharField(blank=True, db_index=True, default=b'oil', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_commodity', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('ticker', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('exchange', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('sec_cik', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('sec_cik_int', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('partner_order', models.IntegerField(default=0)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=500)),
                ('last_edited_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name=b'resource date edited')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=255, null=True)),
                ('system', models.CharField(db_index=True, max_length=255, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, null=True)),
                ('c2id', models.CharField(db_index=True, max_length=255, null=True)),
                ('c2api', models.CharField(db_index=True, max_length=255, null=True)),
                ('c2qty', models.IntegerField(db_index=True, null=True)),
                ('c2submit', models.BooleanField(default=False)),
                ('ibqty', models.IntegerField(db_index=True, null=True)),
                ('ibsubmit', models.BooleanField(default=False)),
                ('trade_freq', models.IntegerField(db_index=True, null=True)),
                ('ibmult', models.IntegerField(db_index=True, null=True)),
                ('c2mult', models.IntegerField(db_index=True, null=True)),
                ('signal', models.CharField(db_index=True, max_length=255, null=True)),
                ('c2instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c2instrument', to='feed.Instrument')),
                ('ibinstrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ibinstrument', to='feed.Instrument')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.Resource'),
        ),
        migrations.AddField(
            model_name='feed',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Instrument'),
        ),
        migrations.AddField(
            model_name='bidask',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Instrument'),
        ),
    ]
